name: Run CI checks # The name will show up on the GitHub Actions dashboard

on: [pull_request] # This workflow will run only on Pull Requests

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Affected apps
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: bahmutov/npm-install@v1
      - run: yarn nx affected --target=build --base=origin/main --parallel
      - run: yarn nx affected --target=lint --base=origin/main --parallel
      - run: yarn nx affected --target=test --base=origin/main --parallel
      - run: yarn nx affected --target=e2e --base=origin/main --parallel